### ISSUE TITLE
Missing image tags on Quay.io

### ISSUE THREAD

**Issue by JoaoBraveCoding** [konveyor/mig-controller#1149]
**Describe the bug**
When installing `release-v1.4.5` using the OperatorHub the installation is not successful because of missing image tags for  `konveyor / velero`  and `konveyor / velero-plugin-for-gcp` on `release-v1.4.5` on Quay.io. 

**To Reproduce**
1. Go to OperatorHub
2. Intall the Crane Operator
3. `oc get all -n openshift-migration`
4. See the `ImgPullErr` with `oc get ev`

**Expected behavior**
Everything should install without errors 

**Additional context**

Also, I edited the CSV to try and install `v1.4.4` and `v1.4.6` and both of them also have missing image tags for some components. I had to downgrade all components back to version `v1.4.3` to have a successful instance running

**Comment by jmontleon** [comment]
The latest breakage is due to these moving to the openshift org. I don't have access to add the keys to the repo add the end of trying to set the quay automated builds back up.

The old ones missing are likely due to docker rate limiting when pulling base images in quay.

Since they're all broken we should probably just switch to using a GH action on all of these like the operator is now doing.

Someone with access is going to have to add the quay robot/token secrets either to the openshift org or repos and then add the GH action. For most of the repos it can be about as simple as below. For velero / velero-restic-restore-helper a little inspiration for building both images can be taken from: https://github.com/konveyor/mig-operator/actions/runs/994102355/workflow#L1-L75

```
    branches:
    - master
    - 'release-*.*.*'
    - 'sprint-*'
    tags:
    - 'release-*.*.*'
  workflow_dispatch:

env:
  REGISTRY: quay.io
  IMAGE_NAME: konveyor/velero
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build container image
        run: docker build . --file build/Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}

      - name: Log into registry
        run: echo "${{ secrets.QUAY_PUBLISH_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_PUBLISH_ROBOT }} --password-stdin

      - name: Push container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}

      - name: Retag container image
        run: docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: push retagged container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        if: ${{ github.ref == 'refs/heads/master' }}
```
