### ISSUE TITLE
VolumeSnapshotProviderTestFailed  UnauthorizedOperation when using an IAM account that only has 'AmazonS3FullAccess'

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/mig-controller#221]
I saw the below when I used an IAM account that only has 'AmazonS3FullAccess' associated with it.  This means it has full access to s3 operations, yet now we are doing a validation of the volume snapshot provider as well and my account had no access to ec2 volume operations.

```
'MigStorage CR'

status:
  conditions:
  - category: Critical
    lastTransitionTime: "2019-07-30T00:32:04Z"
    message: "The Volume Snapshot cloudprovider test failed [UnauthorizedOperation:
      You are not authorized to perform this operation. Encoded authorization failure
      message: <snipped>
      code: 403, request id: 631368fd-90df-4a10-9c9f-17019b3644b9]."
    reason: TestFailed
    status: "True"
    type: VolumeSnapshotProviderTestFailed
```

Looking at this PR https://github.com/fusor/mig-controller/pull/212, it explains how now we are doing a check of 

> For volume snapshot storage, it creates and deletes a small volume

So the error makes sense, the credentials I entered for BackupStorageLocation will not work for VolumeSnashotLocation.

We need to ensure we document the minimal required permissions.
See:  https://heptio.github.io/velero/master/aws-config
