### ISSUE TITLE
Improve modeling of backup storage and volume snapshot properties in the storage CR.

### ISSUE THREAD

**Issue by jortel** [konveyor/mig-controller#239]
The current modeling of the _backup storage_ and _volume snapshot_ provider in Migration CRs is based on Velero CRs.  In doing so, we have replicated some characteristics that I think could be clearer.  Mainly, that the `AWS` provider type really means `s3`.  This along with the flat list of prefixed properties get's even more confusing when using non-AWS providers like _minio_ and _moobaa_.  For example, the CR has properties for awsRegion and awsBucketName and awsS3Url and awsPublicUrl.  I understand that the url can also contain bucket (and perhaps region) information but all this seems overly complicated and confusing when using non-AWS providers.

---

I think there is value in the user being explict about the provider being used.  To support this, We may want to remodel the CRs something like:

Sample YAML:
```
backupStorageProvider:
  aws:
    region: us-east-1
    bucket: mybucket
    s3ForcePathStyle: true
    signatureVersion: 4
    kmsKeyId: 1234
# ---- or -----
  minio:
    url: my.minio.cluster.com
    bucket: mybucket
# ---- or -----
  noobaa:
    url: my.noobaa.redhat.com
    bucket: mybucket
# ---- or -----
  azure:
    storageAccount: myaccount
    resourceGroup: group-1
...
volumeSnapshotProvider:
# more of the same
...
```

This is explicit and support better validation.  The controller can map to velero CRs.
