### ISSUE TITLE
Migration stuck at StagePodsCreated when wrong image is provided in cluster config map

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/mig-controller#657]
With the _migration-cluster-config_ configmap, users can now set custom image FQINs for Stage Pods.  

Using the configmap, I deliberately set the Stage Pods image to something that doesn't exist.

```yml
apiVersion: v1
data:
  [...]
  STAGE_IMAGE: registry.redhat.io/rhcams-1-2/openshift-migration-velero-restic-restore-helper-rhel8@sha256:356e8d9dede186325e3e4f8700cbde7121b6c4dc35c0099b8337c6cfb83049d8
kind: ConfigMap
metadata:
  [...]
  name: migration-cluster-config
  namespace: openshift-migration
```

As expected, the Stage Pods didn't get created and reported `ImagePullBackOff` status:

```sh
pranav@dragonfly mig-controller]$ oc get pods -n mssql-persistent
NAME                                    READY   STATUS             RESTARTS   AGE
mssql-app-deployment-85ddc6946b-h5sd9   1/1     Running            0          1h
mssql-deployment-1-8xw4k                1/1     Running            0          1h
stage-mssql-deployment-1-8xw4k-wnhdc    0/1     ImagePullBackOff   0          2m
``` 

In this case, one would expect migration to enter `StagePodsFailed` since Stage Pods will never be created. However, it gets stuck in `StagePodsCreated` phase forever.

```yml
status:
  conditions:
  - category: Advisory
    lastTransitionTime: "2020-09-04T18:23:47Z"
    message: 'Step: 11/32'
    reason: StagePodsCreated
    status: "True"
    type: Running
  - category: Required
    lastTransitionTime: "2020-09-04T18:20:57Z"
    message: The migration is ready.
    status: "True"
    type: Ready
  - category: Advisory
    durable: true
    lastTransitionTime: "2020-09-04T18:23:13Z"
    message: '[1] Stage pods created.'
    status: "True"
    type: StagePodsCreated
  itinerary: Final
  observedDigest: 9834d071975562d5e2c2eb855bca6950711ded8a0e45af5307fa56cd0f5ba3c7
  phase: StagePodsCreated
  startTimestamp: "2020-09-04T18:20:50Z"
```
Looking at the code, it looks like the only condition for a migration to enter `StagePodsFailed` is when pods don't have healthy claims. But there are other reasons why Stage pods can fail. The one described above is one of them.
