### ISSUE TITLE
MigMigration progress should != 100% when a Mig* resource goes unready

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#660]
## Problem

If a referenced Mig* resource goes unready during MigMigration run, whatever % complete the MigMigration was at is wiped out in the UI and replaced by "100%" in red color. This hides useful information from the user, who may have left their migration running and want to know where it stopped.

![image](https://user-images.githubusercontent.com/7576968/92767593-44382c80-f365-11ea-81fe-3eb786a1d275.png)

This happens in the UI because the MigMigration `Running` status condition is removed when a referenced Mig* resource goes unready.

## Suggested Fix

We should consider making the `Running` condition [durable](https://github.com/konveyor/mig-controller/blob/15830ed79a0e5690e099cdf821261f0cd4b0fa07/pkg/apis/migration/v1alpha1/condition.go#L44) so that it does not get lost when the MigMigration goes to an unready state.

## Examples of pre and post step number wipe from status

**Post-wipe of `Step x/xx`**
```
  status:
    conditions:
    - category: Advisory
      durable: true
      lastTransitionTime: 2020-09-10T16:57:10Z
      message: '[1] Stage pods created.'
      status: "True"
      type: StagePodsCreated
    - category: Critical
      lastTransitionTime: 2020-09-10T16:57:23Z
      message: The referenced `migPlanRef` does not have a `Ready` condition.
      status: "True"
      type: PlanNotReady
    itinerary: Final
    observedDigest: 2d6f69183c5b664aac0522fe21a39d83f28ec7a9ae7bcda6c7160fbdc49ad218
    phase: ResticRestarted
    startTimestamp: 2020-09-10T16:56:52Z
```

**Pre-wipe of `Step x/xx`**
```
status:
  conditions:
  - category: Advisory
    durable: true
    lastTransitionTime: "2020-09-10T16:57:10Z"
    message: '[1] Stage pods created.'
    status: "True"
    type: StagePodsCreated
  - category: Advisory
    lastTransitionTime: "2020-09-10T17:00:26Z"
    message: 'Step: 18/34'
    reason: EnsureQuiesced
    status: "True"
    type: Running
  - category: Required
    lastTransitionTime: "2020-09-10T17:00:25Z"
    message: The migration is ready.
    status: "True"
    type: Ready
  itinerary: Final
  observedDigest: 2d6f69183c5b664aac0522fe21a39d83f28ec7a9ae7bcda6c7160fbdc49ad218
  phase: EnsureQuiesced
  startTimestamp: "2020-09-10T16:56:52Z"
