### ISSUE TITLE
[MIG-119] Show progress of ongoing Velero Backup in MigMigration CR

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/mig-controller#687]
Depends On #685 

**Is your feature request related to a problem? Please describe.**
Currently, `StageBackupCreated` or `FinalBackupCreated` phases do not show the progress of ongoing backup in MigMigration CR. Velero 1.4+, the progress information is available in the _Backup_ resource. It'd be nice to see this progress directly in the MigMigration CR. 

**Describe the solution you'd like**
Velero Backup resource shows the progress of an ongoing Backup:

```yml
  status:
    completionTimestamp: "2020-09-16T15:38:58Z"
    expiration: "2020-10-16T15:38:52Z"
    formatVersion: 1.1.0
    phase: Completed
    progress:
      itemsBackedUp: 25
      totalItems: 26
```
We can bring this information to the _MigMigration_ CR in a new Progress field or condition:

```yml
  status:
    conditions:
    - category: Advisory
      lastTransitionTime: "2020-09-16T15:39:44Z"
      reason: StageBackupCreated
      status: "True"
      type: Running
      progress: 25/26 items backed up
```

**Describe alternatives you've considered**
The solution described above works well for Backup resource. However, there can be multiple PVB resources associated with a Backup. An alternative solution would use another condition to show progress of the ongoing phase.
