### ISSUE TITLE
'Backup' step shows up in pipeline view when running a stage migration

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#765]
**Describe the bug**
I don't think this has any adverse effects, but I think we are showing a step that doesn't actually run in the pipeline view. A `stage` migration never runs the `Backup` step.

This step will never move past `Not started`.

```
    pipeline:
    - completed: "2020-11-11T17:32:16Z"
      message: Completed
      name: Prepare
      started: "2020-11-11T17:31:33Z"
    - message: Not started
      name: Backup
    - completed: "2020-11-11T17:34:09Z"
      message: Completed
      name: StageBackup
```

**To Reproduce**
1. Run a stage migration
2. Look at content of migmigration CR

**Expected behavior**
Only include pipeline steps that will run in the pipeline view.
