### ISSUE TITLE
Bug 1904165: PV discovery screen raises error in mig-ui with new direct migration setup

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#835]
Closed in favor of mig-ui bug: https://github.com/konveyor/mig-ui/issues/1079

**Describe the bug**
https://bugzilla.redhat.com/show_bug.cgi?id=1904165
![image](https://user-images.githubusercontent.com/7576968/101070278-209e1000-3569-11eb-98af-8dd9a7525aad.png)


**To Reproduce**
1. Select namespaces to migrate in mig-ui
2. Proceed to PV discovery step
3. UI will raise error condition warning "Direct image migration is selected and the source cluster openshift-migration/cluster-3 is missing a configured Registry Path"
4. Strangely, the issue seems to be resolved eventually. I checked the spec of the migplan and saw this:
```
  spec:                                                                                                                                                                                                   
    destMigClusterRef:                                                                                                                                                                                    
      name: host                                                                                                                                                                                          
      namespace: openshift-migration                                                                                                                                                                      
    indirectImageMigration: true                                                                                                                                                                          
    indirectVolumeMigration: true
```
My thought is that the initial migplan created by mig-ui is missing the `indirectImageMigration` and `indirectVolumeMigration` settings so the migplan is defaulting to use direct migration.

**Expected behavior**
The migration UI should not throw an error during PV discovery when the user hasn't even had a chance to select indirect/direct migration yet.

This could be solved on controller side by flipping the default and renaming the `directImageMigration` vars, or it could be fixed in mig-ui by making sure the first version of a migplan that is created has `indirectImageMigration` and `indirectVolumeMigration` both set to true.

**Additional context**
I'll file a BZ for this as well.
